-- 1. ISNULL이 아니라 IFNULL을 써야하는 걸 몰라서 오래걸렸고, 2. 경기도 위치 조건 놓침

SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, 'N') AS FREEZER_YN FROM FOOD_WAREHOUSE WHERE WAREHOUSE_NAME LIKE "%경기%" ORDER BY WAREHOUSE_ID;