-- gender 조건 빼먹어서 틀렸당 ...
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, '%Y-%m-%d') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE TLNO IS NOT NULL AND DATE_OF_BIRTH LIKE '_____03___'AND GENDER = 'W'
ORDER BY MEMBER_ID ASC;